+ Fondamenti di Insiemistica e Logica
  - Insiemi, elementi e proposizioni
  - Connettivi logici
  - Diagrammi di Venn
  - Sottoinsiemi
  - Operazioni tra insiemi
    - Intersezione
    - Unione
    - Proprietà distributiva
    - Complemento
    - Differenza insiemistica
+ Insiemi Numerici e Principio di Induzione
  - Insieme dei numeri naturali (N)
  - Principio di Induzione
+ Aritmetica Modulare
  - Definizione di divisione e quoziente e resto
  - Numeri primi
  - Massimo Comun Divisore (MCD)
    - Definizione e proprietà
    - Algoritmo delle divisioni successive
    - Identità di Bézout
  - Minimo Comune Multiplo (MCM)
    - Teorema fondamentale dell'aritmetica
  - Equazioni diofantee
  - Risoluzione di equazioni lineari in due variabili
  - Scrittura in base n
    - Conversione tra diverse basi numeriche

+ Relazioni Binarie e di Equivalenza
- Definizione di relazione binaria
  - Relazioni d'ordine
  - Relazione di equivalenza
    - Proprietà: riflessiva, simmetrica, transitiva
    - Classi di equivalenza
    - Insieme quoziente
  - Partizione di un insieme
  - Classi di resto modulo n (Zn)
    - Relazione di equivalenza modulo n
    - Proprietà e operazioni in Zn

+ Funzioni
  - Definizione di funzione
    - Dominio, codominio e immagine
    - Funzioni iniettive, suriettive e biunivoche
  - Controimmagine di un sottoinsieme
  - Composizione di funzioni

+ Strutture Algebriche
  - Definizione di struttura algebrica
  - Proprietà delle operazioni: associativa e commutativa
  - Elemento neutro e inverso
  - Legge di cancellazione
  - Gruppi
    - Definizione di gruppo e gruppo abeliano
    - Gruppi finiti
    - Gruppo simmetrico
    - Periodo di un elemento
    - Classi di resto modulo n come gruppo
  - Sottogruppi
  - Anelli
    - Definizione e proprietà
    - Esempi di anelli commutativi e non commutativi
  - Campi
    - Definizione e proprietà
    - Esempi di campi numerici
  - Anelli di polinomi
    - Definizione e operazioni con polinomi
    - Divisione tra polinomi
    - Polinomi irriducibili

+ Algebra Lineare
  - Matrici
    - Definizione e operazioni: somma e prodotto per uno scalare
    - Prodotto di matrici
    - Matrice trasposta
    - Matrici simmetriche
  - Matrici invertibili
    - Determinante di una matrice
    - Calcolo dell'inversa di una matrice
  - Sistemi lineari
    - Sistemi lineari omogenei e non omogenei
    - Metodo di Gauss-Jordan
    - Risoluzione di sistemi lineari in Zp
  - Spazi vettoriali
    - Definizione e proprietà
    - Sottospazi vettoriali
    - Combinazioni lineari
    - Sistema di generatori e span
    - Indipendenza lineare
    - Base di uno spazio vettoriale
    - Dimensione di uno spazio vettoriale
    - Formula di Grassmann
    - Somma diretta
  - Omomorfismi (applicazioni lineari)
    - Definizione e proprietà
    - Nucleo e immagine di un omomorfismo
    - Teorema della nullità più rango
    - Isomorfismi
  - Matrice associata ad un omomorfismo
  - Determinante di una matrice
  - Rango di una matrice
    - Calcolo del rango e legame con il determinante
  - Teorema di Rouché-Capelli e Teorema di Cramer
  - Autovalori e Autovettori
    - Definizioni e proprietà
    - Calcolo di autovalori e autovettori
    - Polinomio caratteristico
  - Diagonalizzazione di matrici
    - Matrici simili
    - Criteri di diagonalizzabilità
    - Cambio di base